import { LogLevel, PassedInitialConfig } from 'angular-auth-oidc-client';

export const authConfig: PassedInitialConfig = {
  config: [{
            configId: 'google',
            authority: 'https://accounts.google.com',
            redirectUrl: window.location.origin,
            postLogoutRedirectUri: window.location.origin,
            clientId: '309470803706-erf2diogu09ah4eapebn6ianedf8gqdr.apps.googleusercontent.com',
            scope: 'openid profile email',
            responseType: 'id_token token',
            silentRenew: true,
            autoUserInfo: true,
            useRefreshToken: true,
            ignoreNonceAfterRefresh: true,
            allowUnsafeReuseRefreshToken: true,
            triggerRefreshWhenIdTokenExpired: false,
            silentRenewUrl: window.location.origin + '/silent-renew.html',
            triggerAuthorizationResultEvent: true,
            checkRedirectUrlWhenCheckingIfIsCallback: false,
            renewTimeBeforeTokenExpiresInSeconds: 10,
            secureRoutes: ['http://localhost:8080']
          },
          {
            configId: 'microsoft',
            authority: 'https://login.microsoftonline.com',
            redirectUrl: window.location.origin,
            postLogoutRedirectUri: window.location.origin,
            clientId: 'please-enter-clientId',
            scope: 'openid profile email',
            responseType: 'code',
            silentRenew: true,
            autoUserInfo: true,
            useRefreshToken: true,
            ignoreNonceAfterRefresh: true,
            allowUnsafeReuseRefreshToken: true,
            triggerRefreshWhenIdTokenExpired: false,
            checkRedirectUrlWhenCheckingIfIsCallback: false,
            silentRenewUrl: window.location.origin + '/silent-renew.html',
            renewTimeBeforeTokenExpiresInSeconds: 10,
            secureRoutes: ['http://localhost:8080']
          },
          {
            configId: 'linkedin',
            authority: 'https://www.linkedin.com/oauth/v2/authorization',
            redirectUrl: window.location.origin,
            postLogoutRedirectUri: window.location.origin,
            clientId: 'please-enter-clientId',
            scope: 'openid profile email',
            responseType: 'code',
            silentRenew: true,
            autoUserInfo: true,
            useRefreshToken: true,
            ignoreNonceAfterRefresh: true,
            allowUnsafeReuseRefreshToken: true,
            triggerRefreshWhenIdTokenExpired: false,
            checkRedirectUrlWhenCheckingIfIsCallback: false,
            silentRenewUrl: window.location.origin + '/silent-renew.html',
            renewTimeBeforeTokenExpiresInSeconds: 10,
            secureRoutes: ['http://localhost:8080']
          },
          {
            configId: 'github',
            authority: 'https://github.com/login/oauth/authorize',
            redirectUrl: window.location.origin,
            postLogoutRedirectUri: window.location.origin,
            clientId: 'please-enter-clientId',
            scope: 'openid profile email',
            responseType: 'code',
            silentRenew: true,
            autoUserInfo: true,
            useRefreshToken: true,
            ignoreNonceAfterRefresh: true,
            allowUnsafeReuseRefreshToken: true,
            triggerRefreshWhenIdTokenExpired: false,
            checkRedirectUrlWhenCheckingIfIsCallback: false,
            silentRenewUrl: window.location.origin + '/silent-renew.html',
            renewTimeBeforeTokenExpiresInSeconds: 10,
            secureRoutes: ['http://localhost:8080/']
        }]
}
