spring:
  application:
    name: bytepipe
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: paragparalikar@gmail.com
    password: "urkd uziv tmeo djzx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  springdoc:
    show-actuator: true
    swagger-ui:
      csrf:
        enabled: true
  cache:
    jcache:
      config: classpath:ehcache.xml
      provider: org.ehcache.jsr107.EhcacheCachingProvider
  security:
    oauth2:
      client:
        registration:
          google:
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            introspection-uri: https://www.googleapis.com/oauth2/v1/tokeninfo
            client-id: 309470803706-erf2diogu09ah4eapebn6ianedf8gqdr.apps.googleusercontent.com
            client-secret: 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
          microsoft:
            client-id: eedda50f-e99c-4311-856e-d5433a40a01c
            client-secret: ony8Q~otEq0JkyvAG3Omqkp7i9Mq3aAP.foZedvw
            user-info-uri: https://login.microsoftonline.com/5d6c98ab-f906-4b12-9d24-ee1c69f44321/openid/userinfo
          linkedin:
            client-id: Ov23lipzYgbVE2NBCI6n
            client-secret: bf22f6b30ce23f965a896c9b2852bba1992e771a
            introspection-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://api.linkedin.com/v2/userinfo

bucket4j:
  enabled: true
  cache-to-use: jcache
  filters[0]:
    url: .*
    strategy: first
    cache-name: buckets
    filter-method: servlet
    http-status-code: TOO_MANY_REQUESTS
    hide-http-response-headers: true
    http-response-body: { "message": "Too many requests" }
    metrics:
      enabled: true
      types: CONSUMED_COUNTER,REJECTED_COUNTER
      tags[0]:
        key: IP
        expression: getRemoteAddr()
        types: REJECTED_COUNTER
      tags[1]:
        key: URL
        expression: getRequestURI()
      tags[2]:
        key: USERNAME
        expression: '@securityService.username()'
    rate-limits[0]:
      cache-key: getRemoteAddr()
      bandwidths[0]:
        time: 1
        capacity: 30
        unit: minutes
        fixed-refill-interval: 0
        fixed-refill-interval-unit: minutes

bytepipe:
  base-url: https://localhost:8080
  brand:
    logo-url: https://upload.wikimedia.org/wikipedia/commons/2/28/Firefox_logo%2C_2017.svg
    company-name: Bytepype Co.
    company-address: Pune, MH, India
    social-links:
      facebook: https://www.facebook.com/bytepipe
      twitter: https://www.x.com/bytepipe
      linkedin: https://www.linkedin.com/bytepipe

logging:
  level:
    org:
      springframework:
        security: TRACE
logging.level.org.springframework.security.web.access.ExceptionTranslationFilter: TRACE