spring:
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: paragparalikar@gmail.com
    password: Dark@Horse1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  show-actuator: true

bytepipe:
  base-url: https://localhost:8080
  brand:
    logo-url: https://upload.wikimedia.org/wikipedia/commons/2/28/Firefox_logo%2C_2017.svg
    company-name: Bytepipe Co.
    company-address: Pune, MH, India
    social-links:
      facebook: https://www.facebook.com/bytepipe
      twitter: https://www.x.com/bytepipe
      linkedin: htts://www.linkedin.com/bytepipe
